# Generated by Django 6.0.5 on 2026-05-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='Картинка профиля'),
        ),
    ]
