# Generated by Django 6.0.5 on 2026-05-22 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_number', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во людей')),
                ('check_in_date', models.DateTimeField(verbose_name='Дата заезда')),
                ('check_out_date', models.DateTimeField(verbose_name='Дата выезда')),
                ('status', models.CharField(choices=[('pending', 'Ожидание подтверждения'), ('cancelled', 'Отменено'), ('confirmed', 'Подтверждено')], default='pending', verbose_name='Статус брони')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания брони')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
            },
        ),
        migrations.CreateModel(
            name='Cottage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вместимость')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, upload_to='cottages/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступность для брони')),
            ],
            options={
                'verbose_name': 'Домик',
                'verbose_name_plural': 'Домики',
                'ordering': ['name'],
            },
        ),
    ]
