# Generated by Django 6.0.5 on 2026-05-18 17:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_number', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во людей')),
                ('check_in_date', models.DateTimeField(verbose_name='Дата заезда')),
                ('check_out_date', models.DateTimeField(verbose_name='Дата выезда')),
                ('telephone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. Допускается до 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('status', models.CharField(choices=[('pending', 'Ожидание подтверждения'), ('cancelled', 'Отменено'), ('confirmed', 'Подтверждено')], default='pending', verbose_name='Статус брони')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания брони')),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.cottage', verbose_name='Домик')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
            },
        ),
    ]
