# Generated by Django 6.0.5 on 2026-05-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_cottage_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
    ]
