# Generated by Django 6.0.5 on 2026-05-25 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_comment_text_alter_cottage_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
