# Generated by Django 6.0.5 on 2026-05-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_cottage_image_alter_booking_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
        ),
    ]
