# Generated by Django 6.0.5 on 2026-05-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_cottage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottage',
            name='photo',
        ),
        migrations.AlterField(
            model_name='cottage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cottage_photos', verbose_name='Фото'),
        ),
    ]
